@echo off
REM ****************************************************************************
REM Vivado (TM) v2021.1.1 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Sun Oct 06 23:59:05 +0200 2024
REM SW Build 3286242 on Wed Jul 28 13:10:47 MDT 2021
REM
REM IP Build 3279568 on Wed Jul 28 16:48:48 MDT 2021
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
REM elaborate design
echo "xelab -wto bbaf314d677f4e2d8909c537d39f83e4 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot tb_clock_divier_by_100_behav xil_defaultlib.tb_clock_divier_by_100 -log elaborate.log"
call xelab  -wto bbaf314d677f4e2d8909c537d39f83e4 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot tb_clock_divier_by_100_behav xil_defaultlib.tb_clock_divier_by_100 -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
