@echo off
REM ****************************************************************************
REM Vivado (TM) v2021.1.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sun Oct 06 23:59:07 +0200 2024
REM SW Build 3286242 on Wed Jul 28 13:10:47 MDT 2021
REM
REM IP Build 3279568 on Wed Jul 28 16:48:48 MDT 2021
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim tb_clock_divier_by_100_behav -key {Behavioral:sim_1:Functional:tb_clock_divier_by_100} -tclbatch tb_clock_divier_by_100.tcl -view E:/dev/FPGA/Xlinx/communication_protocols_implementation/I2C/I2C_implementation/I2C_implementation.sim/sim_1/behav/tb_clock_divier_by_100_behav.wcfg -log simulate.log"
call xsim  tb_clock_divier_by_100_behav -key {Behavioral:sim_1:Functional:tb_clock_divier_by_100} -tclbatch tb_clock_divier_by_100.tcl -view E:/dev/FPGA/Xlinx/communication_protocols_implementation/I2C/I2C_implementation/I2C_implementation.sim/sim_1/behav/tb_clock_divier_by_100_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
